### ISSUE TITLE
DPS different than app?

### ISSUE THREAD

**Issue by patrickdemooij9** [alpe123/alpe#1]
Hey!

Great resource! Really like the look and feel of it. I was just wondering how you got to those DPS numbers though. Looking at the csv files in the APK, I couldn't really see how you got to those numbers. 

I assume that you use the PreHitMs and the PostHitAnimMs to calculate the time to hit and go from there, but my calculations are always 50ms off for some reason.

Thanks for taking the time to make the website though! I am mostly asking as I am quite fascinated by going through the csv files

**Comment by alpe123** [comment]
Hi, thanks!

You are right that these stats don't match the ones in-game.

This 50ms adjustment is something that I introduced after noticing a mismatch between real gameplay and the official stats. I have assumed the attack animation or something else may be at fault, adding those missing 50 ms, but unfortunately I wasn't able to get confirmation from the game devs yet.

Generally, the CSV data is meant to feed the game engine, and not to be used as readable information; this is why digesting it can be quite challenging.

**Comment by patrickdemooij9** [comment]
Good point, I haven't done any testing in the app myself and yeah I didn't quite realize that we have no idea what the stats actually do under the hood. Thanks for the explanation!
